export const ApiErrorCodes = {
  AUTH_ERROR: "AUTH_ERROR",
  INVALID_PARAMS: "INVALID_PARAMS",
  RESOURCE_NOT_FOUND: "NOT_FOUND",
  RATE_LIMIT: "RATE_LIMIT",
  NETWORK_ERROR: "NETWORK_ERROR",
  UNKNOWN: "UNKNOWN",
};
